### ISSUE TITLE
Problem with activating with WP 4.7.2

### ISSUE THREAD

**Issue by cmejia1978** [cliffordp/mdl-shortcodes#2]
hi there! Just installed from Wordpress.org repository the mdl shortcode version. It did well until I tried to activate it. I get following error: 

Parse error: syntax error, unexpected T_FUNCTION in /home4/servido2/public_html/cesarmejia/eu/2017/wp-content/plugins/mdl-shortcodes/inc/class-mdl-shortcodes.php on line 87

Thanks!

**Comment by cliffordp** [comment]
Hi. This is the 3rd time you've posted... Please reference my response to your 2nd post about this: https://wordpress.org/support/topic/unable-to-activate-with-wp-4-7-2/#post-8800968

Sorry it's not working for you, but this plugin is no longer maintained.

Thank you.
